### PR TITLE
Change paperclip gem dep. to maintained fork kt-paperclip

### PR DESCRIPTION
**Pull request by megatux**
Also, I updated the Readme a bit.

### CODE REVIEW

**Comment by jarthod** [comment]
I am now using this branch in my project (to support Ruby 3) and I can confirm it's working fine :+1:
cc @tilsammans

**Comment by tilsammans** [comment]
The PR is solid, but I forgot I don't have write access to this repo. Will take that up with @mrrooijen.

**Comment by mrrooijen** [comment]
@tilsammans thanks for picking this up. I've provided access to your account. You already have access to publish on RubyGems.

**Comment by tilsammans** [comment]
Released version 0.1.0 contains this change.

**Pull request merged**
